#!/bin/bash

#rm -rf node_modules/@serialport/bindings-cpp/build/Release/bindings.node
#rm -rf node_modules/sqlite3/build/Release/node_sqlite3.node

#rm -rf node_modules/sqlite3/lib/binding/napi-v6-win32-unknown-x64/node_sqlite3.node
#rm -rf node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-x64/node_sqlite3.node

#mkdir -p node_modules/sqlite3/lib/binding/napi-v6-win32-unknown-x64
#mkdir -p node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-x64

#cp build_node/sqlite3/lib/binding/napi-v6-win32-unknown-x64/node_sqlite3.node node_modules/sqlite3/lib/binding/napi-v6-win32-unknown-x64/node_sqlite3.node
#cp build_node/sqlite3/lib/binding/napi-v6-darwin-unknown-x64/node_sqlite3.node node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-x64/node_sqlite3.node
# if [ ! -n "$VUE_APP_ENV" ]
# then
# fi
