name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create config files and set env
        run: |
          echo "Decoding and creating .env file..."
          $encodedContent = "${{ secrets.ENV_FILE }}"
          $decodedBytes = [System.Convert]::FromBase64String($encodedContent)
          $decodedText = [System.Text.Encoding]::UTF8.GetString($decodedBytes)
          $decodedText | Out-File -FilePath .env -Encoding UTF8
          echo ".env file created"
          
          echo "Reading GH_TOKEN..."
          $envContent = Get-Content .env
          $GH_TOKEN = ($envContent | Select-String "GH_TOKEN=(.*)").Matches.Groups[1].Value
          echo "Setting GH_TOKEN to environment"
          echo "GH_TOKEN=$GH_TOKEN" >> $env:GITHUB_ENV
          echo "Environment variables set"
        shell: pwsh

      - name: Check env file
        run: |
          echo "Checking .env file content:"
          Get-Content .env
        shell: pwsh

      - name: Install dependencies
        run: npm ci

      - name: Build and publish
        env:
          GH_TOKEN: ${{ env.GH_TOKEN }}
        run: npm run deploy